package com.myspace.workflow_engine_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ticket implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "TICKET_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TICKET_ID_SEQ", name = "TICKET_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String endpointId;

	private java.lang.String partnerId;

	private java.lang.Integer priority;

	private java.lang.String conditionId;

	private java.lang.String siteId;

	private java.lang.String clientId;

	private java.lang.String resourceId;

	private java.lang.String alertId;

	private java.lang.String conditionName;

	private java.lang.String ticketDescription;

	private java.lang.String ticketTitle;

	private java.lang.String assignTo;

	private java.lang.String ticketStatus;

	private java.lang.String ticketId;

	public ticket() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEndpointId() {
		return this.endpointId;
	}

	public void setEndpointId(java.lang.String endpointId) {
		this.endpointId = endpointId;
	}

	public java.lang.String getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(java.lang.String partnerId) {
		this.partnerId = partnerId;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public java.lang.String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(java.lang.String conditionId) {
		this.conditionId = conditionId;
	}

	public java.lang.String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(java.lang.String siteId) {
		this.siteId = siteId;
	}

	public java.lang.String getClientId() {
		return this.clientId;
	}

	public void setClientId(java.lang.String clientId) {
		this.clientId = clientId;
	}

	public java.lang.String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(java.lang.String resourceId) {
		this.resourceId = resourceId;
	}

	public java.lang.String getAlertId() {
		return this.alertId;
	}

	public void setAlertId(java.lang.String alertId) {
		this.alertId = alertId;
	}

	public java.lang.String getConditionName() {
		return this.conditionName;
	}

	public void setConditionName(java.lang.String conditionName) {
		this.conditionName = conditionName;
	}

	public java.lang.String getTicketDescription() {
		return this.ticketDescription;
	}

	public void setTicketDescription(java.lang.String ticketDescription) {
		this.ticketDescription = ticketDescription;
	}

	public java.lang.String getTicketTitle() {
		return this.ticketTitle;
	}

	public void setTicketTitle(java.lang.String ticketTitle) {
		this.ticketTitle = ticketTitle;
	}

	public java.lang.String getAssignTo() {
		return this.assignTo;
	}

	public void setAssignTo(java.lang.String assignTo) {
		this.assignTo = assignTo;
	}

	public java.lang.String getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(java.lang.String ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

	public java.lang.String getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(java.lang.String ticketId) {
		this.ticketId = ticketId;
	}

	public ticket(java.lang.Long id, java.lang.String endpointId,
			java.lang.String partnerId, java.lang.Integer priority,
			java.lang.String conditionId, java.lang.String siteId,
			java.lang.String clientId, java.lang.String resourceId,
			java.lang.String alertId, java.lang.String conditionName,
			java.lang.String ticketDescription, java.lang.String ticketTitle,
			java.lang.String assignTo, java.lang.String ticketStatus,
			java.lang.String ticketId) {
		this.id = id;
		this.endpointId = endpointId;
		this.partnerId = partnerId;
		this.priority = priority;
		this.conditionId = conditionId;
		this.siteId = siteId;
		this.clientId = clientId;
		this.resourceId = resourceId;
		this.alertId = alertId;
		this.conditionName = conditionName;
		this.ticketDescription = ticketDescription;
		this.ticketTitle = ticketTitle;
		this.assignTo = assignTo;
		this.ticketStatus = ticketStatus;
		this.ticketId = ticketId;
	}
}